# Версия плагина — меняй только эту строку
$version = "1.0.3"

Write-Host "Using version: $version"

$text = @"
// Generated by update-version.ps1
using System.Reflection;

[assembly: AssemblyVersion("$version.0")]
[assembly: AssemblyInformationalVersion("$version")]
"@

$text | Out-File "$PSScriptRoot\..\GitVersion.cs" -Encoding utf8

$basePath = Join-Path $PSScriptRoot "..\QuickLook.Plugin.Metadata.Base.config"
$configPath = Join-Path $PSScriptRoot "..\QuickLook.Plugin.Metadata.config"

if (Test-Path $basePath) {
    $xml = [xml](Get-Content $basePath -Encoding UTF8)

    if ($null -ne $xml.Metadata) {
        $xml.Metadata.Version = $version
    }

    $xml.Save($configPath)
}

Write-Host "Version set to $version"
